# build stage(react.js 빌드)
FROM node:lts-alpine as build-stage
WORKDIR /app
COPY package*.json ./ 
RUN npm install
COPY . .
RUN npm run build 

# production stage(nginx 사용하여 동작)
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
